import { Validator, Rule } from "../types";


export default {
    required: { required: true, trigger: 'blur', message: '{label}不得为空' } as Rule,
    filled: { required: true, trigger: 'blur', message: '{label}不得为空' } as Rule,
    empty: { trigger: 'blur', message: '{label}必须为空' } as Rule,
    pattern: { trigger: 'blur', message: '{label}格式不正确' } as Rule,
    minLength: { trigger: 'blur', message: '不得少于{0}个字符' } as Rule,
    maxLength: { trigger: 'blur', message: '不得超过{0}个字符' } as Rule,
    rangeLength: { trigger: 'blur', message: '请输入{0}-{1}个字符' } as Rule,
    min: { trigger: 'blur', message: '不能小于{0}' } as Rule,
    max: { trigger: 'blur', message: '不能大于{0}' } as Rule,
    range: { trigger: 'blur', message: '应该在{0}-{1}之间' } as Rule,
    string: { trigger: 'input+blur', message: '请输入字符串' } as Rule,
    number: { trigger: 'input+blur', message: '请输入数字' } as Rule,
    numeric: { trigger: 'input+blur', message: '请输入数字' } as Rule,
    alpha: { trigger: 'input+blur', message: '请输入字母' } as Rule,
    alphaNumeric: { trigger: 'input+blur', message: '请输入字母或数字' } as Rule,
    integer: { trigger: 'input+blur', message: '请输入整数' } as Rule,
    decimal: { trigger: 'input+blur', message: '请输入小数' } as Rule,
    email: { trigger: 'blur', message: '请输入正确的邮箱' } as Rule,
    ip: { trigger: 'blur', message: '请输入正确的 IP' } as Rule,
    ipRange: { trigger: 'blur', message: '请输入正确的 IP 段' } as Rule,
    port: { trigger: 'blur', message: '请输入正确的端口' } as Rule,
    url: { trigger: 'blur', message: '请输入正确的 URL' } as Rule,
    macAddress: { trigger: 'blur', message: '请输入正确的 MAC 地址' } as Rule,
    md5: { trigger: 'blur', message: '请输入正确的 MD5' } as Rule,
    equals: { trigger: 'blur', message: '必须与{0}相同' } as Rule,
    confirmed: { validate: 'equals', trigger: 'blur', message: '两次输入的密码不一致' } as Rule,
    includes: { trigger: 'blur', message: '必须包含{0}' } as Rule,
    excludes: { trigger: 'blur', message: '不能包含{0}' } as Rule,
    included: { trigger: 'blur', message: '必须包含在{0}中' } as Rule,
    excluded: { trigger: 'blur', message: '不能包含在{0}中' } as Rule,
    unique: { validate: 'excluded', trigger: 'blur', message: '该{label}已经存在' } as Rule,
    '^az': { trigger: 'input+blur', message: '以小写字母开头' } as Rule,
    '^az09': { trigger: 'input+blur', message: '以小写字母或数字开头' } as Rule,
    'az09$': { trigger: 'blur', message: '以小写字母或数字结尾' } as Rule,
    'azAZ09$': { trigger: 'blur', message: '以字母或数字结尾' } as Rule,
    '^09$': { trigger: 'blur', message: '以数字组成' } as Rule,
    '^azAZ09$': { trigger: 'input+blur', message: '以字母或数字组成' } as Rule,
    '^azAZ09-$': { trigger: 'input+blur', message: '以字母、数字或"-"组成' } as Rule,
    '^azAZ09_$': { trigger: 'input+blur', message: '以字母、数字或"_"组成' } as Rule,
    'without--': { trigger: 'input+blur', message: '不能连续出现中划线' } as Rule,
    'without__': { trigger: 'input+blur', message: '不能连续出现下划线' } as Rule,
} as { [prop: string]: Rule };
